#!/usr/bin/env ts-node
/**
 * Clean all build artifacts and generated content.
 *
 * The vault is the single source of truth for all content. Everything
 * under content/ is generated by scripts/export-hugo.ts and is disposable;
 * this script nukes it wholesale along with Hugo's build artifacts.
 *
 * Removes:
 *   - content/                       (entire generated content tree)
 *   - public/                        (Hugo's rendered output)
 *   - resources/_gen/                (Hugo's image/asset cache)
 *   - .hugo_build.lock
 *
 * Usage:
 *   npm run clean
 *   npm run clean -- --verbose   # log every path removed
 *   npm run clean -- --dry-run   # report what would be removed without removing
 */

import * as fs from "fs";
import * as path from "path";

const REMOVE_PATHS = [
    "content",
    "public",
    "resources/_gen",
    ".hugo_build.lock",
];

const ROOT = path.resolve(__dirname, "..");

const args = process.argv.slice(2);
const verbose = args.includes("--verbose") || args.includes("-v");
const dryRun = args.includes("--dry-run") || args.includes("-n");

function removeIfPresent(target: string): void {
    const abs = path.isAbsolute(target) ? target : path.join(ROOT, target);
    if (!fs.existsSync(abs)) {
        if (verbose) console.log(`  skip (missing): ${path.relative(ROOT, abs)}`);
        return;
    }
    if (dryRun) {
        console.log(`  would remove: ${path.relative(ROOT, abs)}`);
        return;
    }
    fs.rmSync(abs, { recursive: true, force: true });
    console.log(`  removed: ${path.relative(ROOT, abs)}`);
}

function main(): void {
    console.log(
        dryRun
            ? "Cleaning build artifacts (dry run)..."
            : "Cleaning build artifacts...",
    );

    for (const target of REMOVE_PATHS) {
        removeIfPresent(target);
    }

    console.log(dryRun ? "Done (dry run)." : "Done.");
}

main();
